% Author: Lorenz Leutgeb <e1127842@student.tuwien.ac.at>

% Expected answer set:
%
% {scheduled(1,3), scheduled(2,1), scheduled(2,3), scheduled(3,2), scheduled(3,3), scheduled(4,1), scheduled(4,2), scheduled(5,1), scheduled(5,3), scheduled(6,1), scheduled(1,2), scheduled(2,2), scheduled(5,2), scheduled(6,2)}

nextday(1,2). % Tuesday
nextday(2,3). % Wednesday
nextday(3,4). % Thursday
nextday(4,5). % Friday
nextday(5,6). % Saturday
nextday(6,7). % Sunday

nextroom(1,2).
nextroom(2,3).


course(c1,1,3).
course(c1,2,1).
course(c1,2,3).
course(c1,3,2).
course(c1,3,3).

course(c2,4,1).
course(c2,4,2).
course(c2,5,1).
course(c2,5,3).
course(c2,6,1).

course(c3,1,2).
course(c3,2,2).
course(c3,5,2).
course(c3,6,2).

sumrooms(1,2).
sumrooms(2,3).
sumrooms(3,2).
sumrooms(4,2).
sumrooms(5,3).
sumrooms(6,2).
sumrooms(7,0).

sumdays(1,4).
sumdays(2,6).
sumdays(3,4).
